---
- name: "apt package update"
  become: true
  apt:
    update_cache: yes
- name: "apt package upgrade"
  become: true
  apt:
    upgrade: yes
- name: "Remove redundant dependencies"
  become: true
  apt:
    autoremove: yes
- name: "Install server required dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
- name: "Install the package pm2."
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "move env variables to /etc/profile.d/"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d/