---
- name: "Update packages."
  become: true
  apt:
    force_apt_get: yes
    update_cache : true

- name: Install nodejs prerequisites
  apt:
    name:
      - apt-transport-https
      - gcc
      - g++
      - make
    state: present

- name: "Install server required dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes


- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present