---

- name: "Ship tar file to ec2 instance and extract it"
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: ~/

- name: "Install backend server's package."
  npm:
    path: ~/

- name: "Stop currently running app"
  ignore_errors: true
  shell: |
    pm2 stop server

- name: "Start the app"
  shell: |
    pm2 start npm -- start --name server
